import React, { useEffect, useState, useCallback, useRef } from 'react';
import { useRemirror } from '../hooks/useRemirror';
import type { DailyBriefDTO, RegenStatusDTO, AnthropicStatusDTO, BriefStreamEvent } from '@shared/types';
import { BriefCard } from '../ui/BriefCard';
import { PastBriefRow } from '../ui/PastBriefRow';
import { NoApiKeyState } from '../ui/BriefEmptyStates';

interface Props { onNavigateToSettings: () => void; }

export function Brief({ onNavigateToSettings }: Props) {
  const api = useRemirror();
  const [today, setToday] = useState<DailyBriefDTO | null>(null);
  const [past, setPast] = useState<DailyBriefDTO[]>([]);
  const [regenStatus, setRegenStatus] = useState<RegenStatusDTO>({ used: 0, cap: 2, locked: false });
  const [anthropicStatus, setAnthropicStatus] = useState<AnthropicStatusDTO | null>(null);
  const [streamingMarkdown, setStreamingMarkdown] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const activeGenId = useRef<string | null>(null);

  const refresh = useCallback(async () => {
    const [t, p, rs, as] = await Promise.all([
      api.briefToday(), api.briefListPast(30), api.briefRegenStatus(), api.anthropicStatus(),
    ]);
    setToday(t); setPast(p); setRegenStatus(rs); setAnthropicStatus(as);
  }, [api]);

  useEffect(() => {
    refresh();
    const off = api.onBriefStream((e: BriefStreamEvent) => {
      if (activeGenId.current && e.generationId !== activeGenId.current) return;
      if (e.kind === 'text_delta') {
        setStreamingMarkdown(prev => (prev ?? '') + e.delta);
      } else if (e.kind === 'done') {
        activeGenId.current = null;
        setStreamingMarkdown(null);
        setError(null);
        setBusy(false);
        refresh();
      } else if (e.kind === 'error') {
        activeGenId.current = null;
        setStreamingMarkdown(null);
        setError(e.message);
        setBusy(false);
      }
    });
    return off;
  }, [api, refresh]);

  async function handleGenerate() {
    setError(null); setBusy(true); setStreamingMarkdown('');
    try {
      const { generationId } = await api.briefGenerate();
      activeGenId.current = generationId;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      setStreamingMarkdown(null); setBusy(false);
      if (msg.includes('ANTHROPIC_API_KEY_MISSING')) {
        setError('Set up your Anthropic API key in Settings.');
      } else {
        setError(msg);
      }
    }
  }

  if (anthropicStatus === null) return <div className="p-6 text-muted">Loading…</div>;

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="mb-6">
        <h2 className="text-text text-lg font-semibold mb-1">Today, {new Date().toLocaleDateString([], { weekday: 'long', month: 'long', day: 'numeric' })}</h2>
        <p className="text-quiet text-xs">An end-of-day reflection generated by Claude from today's recorded data.</p>
      </div>

      {!anthropicStatus.hasKey ? (
        <NoApiKeyState onSetupKey={onNavigateToSettings} />
      ) : (
        <BriefCard
          brief={today}
          streamingMarkdown={streamingMarkdown}
          regenStatus={regenStatus}
          error={error}
          onGenerate={handleGenerate}
          onRegenerate={handleGenerate}
          busy={busy}
        />
      )}

      {past.length > 0 && (
        <div className="mt-10">
          <h3 className="text-[10px] uppercase tracking-[1.5px] text-muted font-semibold mb-2">Past briefs</h3>
          <div>
            {past.map(b => <PastBriefRow key={b.date} brief={b} />)}
          </div>
        </div>
      )}
    </div>
  );
}
